from BoardOOP.Board import Board

from Constants import constant

board = Board()
'''
board.print_board()
board.add_piece((3,3),constant.WHITE_PIECE)
board.print_board()
print(board.white_pieces[(3,3)])

board.add_piece((3,4),constant.BLACK_PIECE)
board.print_board()
print(board.black_pieces[(3,4)])
print(board.white_pieces[(3,3)])

board.add_piece((3,5),constant.WHITE_PIECE)
board.print_board()
print(board.white_pieces[(3,5)])
print(board.black_pieces[(3,4)])
print(board.white_pieces[(3,3)])

board.add_piece((4,4),constant.BLACK_PIECE)
board.print_board()
print(board.black_pieces[(4,4)])
print(board.white_pieces[(3,5)])
print(board.black_pieces[(3,4)])
print(board.white_pieces[(3,3)])

board.add_piece((2,5),constant.BLACK_PIECE)
board.add_piece((4,5),constant.BLACK_PIECE)
print(board.check_one_piece_elimination((3,5),constant.WHITE_PIECE))
board.perform_elimination((3,5),constant.WHITE_PIECE)
board.add_piece((10,10),constant.WHITE_PIECE)
print(board.white_pieces)
print(board.black_pieces)
a = board.apply_placement((2,2),constant.WHITE_PIECE)
b = board.apply_move((2,2), 1, constant.WHITE_PIECE)
print(board)
print(board.white_pieces)
print(board.black_pieces)
print(board.white_eliminate_pieces)
print(board.black_eliminate_pieces)
print(a, b)
e = board.update_board((2,2),constant.WHITE_PIECE)
print(board.get_piece((2,3)))
print("UNDO MOVE")
board.undo_move((2,2),constant.WHITE_PIECE, e)
print(board.get_piece((2,3)))
print(board)
'''
board.update_board((2,2),constant.WHITE_PIECE)

board.update_board((3,2),constant.BLACK_PIECE)
print("___________________________")
print(board.get_piece((2,2)))
print(board.get_piece((3,2)))
print("___________________________")
e = board.update_board((4,2),constant.WHITE_PIECE)
print(board.white_pieces)
print("UNDO MOVE -------------------------------------")
board.undo_move((4,2),constant.WHITE_PIECE,e)
print(board)
print(board.white_pieces)
print(board.black_pieces)
print("*"*20)
print(board.get_piece((2,2)))
print(board.get_piece((3,2)))
print("*"*20)
print(board.free_squares)
print(board.get_placement_list(constant.WHITE_PIECE))
print(len(board.get_placement_list(constant.WHITE_PIECE)))
print(board.get_move_list(constant.WHITE_PIECE))
print(board.get_move_list(constant.BLACK_PIECE))
print(board.get_piece((2,2)))
print(board.get_piece((3,2)))
print(board.update_actions(constant.BLACK_PIECE))
