'''
THIS FILE CONTAINS THE GLOBAL VARIABLES FOR THE GAME BOARD
INCLUDE IN gameBoard.py

'''

# GLOBAL VARIABLES
BOARD_SIZE = 8
MAX_MOVETYPE = 8
MAX_NUM_PIECES = 12
# space types
FREE_SPACE = '-'
CORNER_PIECE = 'X'
WHITE_PIECE = 'O'
BLACK_PIECE = '@'
INVALID_SPACE = '.'

# phases
PLACEMENT_PHASE = 0
MOVING_PHASE = 1

# search constants

# IDDFS and DLS
FAILURE = None
CUTOFF = -2
NO_SOLUTION = -3
MAX_DEPTH = 100